### ISSUE TITLE
Only Homepage loads - other sites won't open

### ISSUE THREAD

**Issue by ZEAL-IT** [SAP-samples/btp-resource-consumption-monitor#13]
Hey guys,
the homepage loads successfully, but all other links won't open:
Homepage;
![image](https://github.com/SAP-samples/btp-resource-consumption-monitor/assets/100712993/2d6d1698-d71d-4d4d-a24f-d87d6376bbf6)

Configure Alerts (same error for other sites)
![image](https://github.com/SAP-samples/btp-resource-consumption-monitor/assets/100712993/7c75152f-bb76-4aba-b5bd-1f42f706cf82)
Any idea what's happening or missing here?

Any help is appreciated, thank you very much,
Christopher

**Comment by willemi069808** [comment]
Hi Christopher, for this specific issue kindly refresh the HTML5 repo twice as mentioned here: https://github.com/SAP-samples/btp-resource-consumption-monitor?tab=readme-ov-file#known-issues. This is a temporary bug in Work Zone which will be corrected in a next version.

Please confirm if, after the refresh, the application loads successfully, or whether there is a next error in retrieving the "$metadata" as I expect a bug was introduced in the last commit to this repository.

**Comment by ZEAL-IT** [comment]
> Hi Christopher, for this specific issue kindly refresh the HTML5 repo twice as mentioned here: https://github.com/SAP-samples/btp-resource-consumption-monitor?tab=readme-ov-file#known-issues. This is a temporary bug in Work Zone which will be corrected in a next version.
> 
> Please confirm if, after the refresh, the application loads successfully, or whether there is a next error in retrieving the "$metadata" as I expect a bug was introduced in the last commit to this repository.

Hello @willemi069808 thank you, in the meanwhile I found the "known issue" and I wanted to answer but you were quick. You are right, I'm facing now the $metadata error. So I assume I'll have to wait for a fix, is that correct?

**Comment by willemi069808** [comment]
Hi Christopher, I'm in the process of fixing that error, and what should help to resolve this is to make a small change in 2 files:
- /cf/app/btprcreport/webapp/manifest.json
- /cf/app/managealerts/webapp/manifest.json
each on line 20: change the URI: remove the first/leading slash `/`

Then rebuild and redeploy etc.

**Comment by willemi069808** [comment]
The $metadata error should be resolved with 97749d3. After deployment, if the same error still pops-up in the browser, you can do a clear-cache-and-reload in your browser to make sure you load the latest version.

**Comment by ZEAL-IT** [comment]
Awesome, works great. Thank you so much
