### ISSUE TITLE
Error in cf deploy Process

### ISSUE THREAD

**Issue by and23jul** [SAP-samples/btp-resource-consumption-monitor#19]
Hi,

I got the error as attached when trying to deploy...Please help.

Just for context, I tried to deploy once before while forgetting to instantiate HANA Cloud - Tools plan. This log attached is on second attempt after I instantiate HANA Cloud - Tools (after 1st attempt  some of the services instantiation have been created, but 2 were failing. Screen capture attached.)
![Error](https://github.com/user-attachments/assets/aa6a0935-a29b-4395-aac3-e1fb7fab8adf)

Logs:
[OPERATION.log](https://github.com/user-attachments/files/16244274/OPERATION.log)

Best Regards

Andre Julius

**Comment by willemi069808** [comment]
Hi Andre Julius,

Before re-attempting a deployment, you should clean up the service instances that are in error state. So you should delete the 'btprc-db' and 'btprc-auth' instances. Also note that the Job Scheduler and Authorization service should be deployed simultaneously, so if you redeploy 'btprc-auth' you should also redeploy 'btprc-scheduler' (so, you should also remove this one before doing the redeployment).

For the database, having a subscription to HANA Tools alone is not sufficient, you have to create a HANA database itself as well. This you can do via HANA Tools, see: https://help.sap.com/docs/hana-cloud/sap-hana-cloud-administration-guide/create-sap-hana-database-instance-using-sap-hana-cloud-central
