### ISSUE TITLE
A Few Doubts Regarding the Usage

### ISSUE THREAD

**Issue by and23jul** [SAP-samples/btp-resource-consumption-monitor#20]
It's a great app Willem
1. For "Cost By Tags",  aggregation will not happen assuming tags are given on the Service Level Instead of Subaccount Level?
2. Is there a way I can toggle show/hide some node e.g. Subaccount / Services that are obsolete already? or Availability Zone, for that is a bit meaningless.
3. If I skipped the SAC process, I just need to redo the Workzone Deployment step again? will I need to reconfigure the Workzone(in the service)?

Some issue / inconvinience observed
- when I change tags lets say on Service level (below subaccount), the tree on the left refreshed to change to subaccount level, and I have to drilldown again
- When I create tags, sometimes, they produce a blank tag, but did not show me nor allow me to fill up the tags until I create again

**Comment by willemi069808** [comment]
Hi Andre,

Thanks for your feedback.

Regarding your questions:

1. Correct, aggregations are visible in the SAC view of this data, but not in the Fiori view.
2. In the `Manage Tags` application there is an `exclude' setting which will hide this item from the cross-charging end-user views. If you have subaccounts or directories which are completely not used anymore, the tool was maybe loaded with too much historic information?
3. If you want to enable SAC after the initial deployment, you will have to do the Work Zone deployment again, in which you first should increase the version number of your package (here: https://github.com/SAP-samples/btp-resource-consumption-monitor/blob/main/workzone/manifest.json#L5) so your upload is accepted as a new version.

Regarding your issues:

- Correct, this is a bit annoying from UX point of view, but it is the default behavior of the odata v2 treetable. According to the CAP roadmap an odata v4 treetable might be supported soon, which we can explore then as it might improve/fix this behavior.
- It's unclear to me what you refer to here, but I did notice that the selected subaccount/service will have empty values for the existing tags while the side-panel is open. I hope that the v4 version mentioned above also rectifies this.

Please let me know if you have any other feedback.

**Comment by and23jul** [comment]
Hi Willem,

1. Correct, aggregations are visible in the SAC view of this data, but not in the Fiori view. --> _aww....shucks...I don't have my hands on SAC component yet...but now as I have started painstakingly updating the tags, I hope the tags are not done when I increase the version in the future?_
2. In the Manage Tags application there is an `exclude' setting which will hide this item from the cross-charging end-user views. If you have subaccounts or directories which are completely not used anymore, the tool was maybe loaded with too much historic information? --> _OK will use the exclude, indeed, they loaded all the historical elements that supposedly have been deleted, and those regions as a separate item, which supposedly is not really relevant in the tree_
3. If you want to enable SAC after the initial deployment, you will have to do the Work Zone deployment again, in which you first should increase the version number of your package (here: https://github.com/SAP-samples/btp-resource-consumption-monitor/blob/main/workzone/manifest.json#L5) so your upload is accepted as a new version.--> Still not very clear to me at this moment, but I will look at this when the need arise, thanks :)
4. It's unclear to me what you refer to here, but I did notice that the selected subaccount/service will have empty values for the existing tags while the side-panel is open. I hope that the v4 version mentioned above also rectifies this. --> _yesterday, when I use corporate laptop, when I "create tag" nothing happen, and when I "create tag again" only then they show me the tag I was supposed to have created the first time. today with my personal laptop I don't have that issue though...weird_

Best Regards


Andre Julius

**Comment by and23jul** [comment]
@willemi069808 would you be able to advise for number 1 question please? I have gained access to SAC, but I am afraid to be losing my tags which I have set before.

**Comment by willemi069808** [comment]
Hi @and23jul
Sorry I don't really understand your question. You have configured the tags, and they work? Not sure what you are referring to with 'increase the version in the future'. If there are future versions of the tool, any update will have to be done to preserve configurations, whether it is tags or forecast settings, alerts, ... As long as you don't click on 'delete all tags' they remain in the database. You can also export them from the database if you want. It's a normal table in your HDI container.
