### ISSUE TITLE
Cannot validate imported SAC models

### ISSUE THREAD

**Issue by nikolicm55** [SAP-samples/btp-resource-consumption-monitor#22]
Hi Wiilem,

We have imported FinOps package into our SAC tenant and have tried a verification, encounting the  following problem

At first error, we have modified Data Source as per documentation

Server Error: Error [Server]: (#42208) Can't read the view : BTPRC_MONITORING:BTPRC_MONITORING/CV_CommercialMeasuresByTags::[], reason: Can't read the view : BTPRC_MONITORING:BTPRC_MONITORING/CV_CommercialMeasuresByTags
Correlation ID: 27477031-1019-4411-b812-920138376922_

However, that have produced a new error
Server Error: Error [Server]: (#42208) Can't read the view : BTPRC_DEV:BTPRC_DEV/CV_CommercialMeasuresByTags::[], reason: **Not authorized :** Detailed info for this error can be found with guid 'A7CBDDCE5AC4E840AD9DE18716ED6FBB'
Correlation ID: 31030797-3222-4715-8639-566136789342

Can you please confirm if above error is related to already documented Know Issue about missing privilage "_SYS_BI::BIMC_PROPERTIES"

Best Regards,
Mario Nikolic

**Comment by willemi069808** [comment]
Hi Mario,

Yes, 100% correct. You can either upgrade your HANA, or manually assign the privilege to the user via HANA Cloud Central.

**Comment by nikolicm55** [comment]
Issue has been resolved
