### ISSUE TITLE
Workzone site not loading.

### ISSUE THREAD

**Issue by arunkrishnamoorthy** [SAP-samples/btp-resource-consumption-monitor#25]
After deploying the content package to the workzone, I was able to work with the application. After the scheduler ran, i was also able to see the data. After sometime, the workzone site stopped working, i am getting the following error. How can i resolve this? 
The CAP server is running, and i am able to open the application from the links in the HTML5 repository. Only when i open the workzone site i am getting this error.

<img width="1382" alt="image" src="https://github.com/user-attachments/assets/1eb5935e-802f-4a8b-89bc-27d7a13b4f76">

<img width="1337" alt="image" src="https://github.com/user-attachments/assets/184c9a35-fc14-4b2f-af96-576e9f69730e">

**Comment by willemi069808** [comment]
Hi Arun,
Is the error still present? It is unrelated to this application and seems like a temporary issue with SAP Work Zone. I'd suggest to clear the cache of the browser and try again. If the issue persist, you can open an incident with SAP.

**Comment by akrishnamoorthy1988** [comment]
Hi @willemi069808 , 

Thank you for responding. This issue is not occurring any more. Had to delete the content package and site and redeployed everything and it seem okay now.
