### ISSUE TITLE
The Highest Credit Forecasts and Forecast Breakdown tiles are not showing data.

### ISSUE THREAD

**Issue by Bitupatra1234567** [SAP-samples/btp-resource-consumption-monitor#32]
![btp1](https://github.com/user-attachments/assets/e11f2f46-1376-4a49-9a57-1984a64d1a99)
![btp2](https://github.com/user-attachments/assets/d4352fd8-db53-4122-b77f-121d80757794)

**Comment by willemi069808** [comment]
See #24
