### ISSUE TITLE
mbt build issue

### ISSUE THREAD

**Issue by madhumr3107** [SAP-samples/btp-resource-consumption-monitor#37]
Hi Willem,

As discussed, when i am try to enter the command mbt build getting the error as " [2024-12-18 08:00:55] ERROR the "before-all"" build failed: could not execute the "npm run build:cf" command: exit status 1
make: *** [Makefile_20241218080043.mta:28: pre_build] Error 1
Error: could not build the MTA project: could not execute the "make -f Makefile_20241218080043.mta p=cf mtar= strict=true mode=" command: exit status 2". 

Steps we followed to is;
1. we cloned the git hub repository to the BAS
2. we added our email id for notification.
3. later went to terminal and enterd the command npm install and got few vulernabilites and later removed the line ctz from packagae.json. and then executed npm install ts-node and it was successfull.
4. then while exeucting the mbt install getting that error.

kindly help to reslove the same asap.

Regards,
Madhu MR

**Comment by willemi069808** [comment]
Hi, please post the full log output which mentions the exact error: use a terminal window and execute `npm install` and `mbt build` and provide the full log.

**Comment by madhumr3107** [comment]
Hi Willem,

Please find the compelete logs of the requested commands.

user: cf $ npm install

up to date, audited 783 packages in 622ms

82 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
user: cf $ 
user: cf $ mbt build
[2024-12-18 13:33:42]  INFO Cloud MTA Build Tool version 1.2.18
[2024-12-18 13:33:42]  INFO generating the "Makefile_20241218133342.mta" file...
[2024-12-18 13:33:42]  INFO done
[2024-12-18 13:33:42]  INFO executing the "make -f Makefile_20241218133342.mta p=cf mtar= strict=true mode=" command...
[2024-12-18 13:33:42]  INFO validating the MTA project
[2024-12-18 13:33:42]  INFO running the "before-all" build...
[2024-12-18 13:33:42]  INFO executing the "npm run build:cf" command...

> btp-resource-consumption@2.1.0 build:cf
> rimraf @cds-models resources mta_archives gen && cds-ts build --production

.building project [/home/user/projects/btp-resource-consumption-monitor/cf], clean [true]
cds-dk [8.5.1], cds [8.5.1], compiler [5.5.2], home [/home/user/projects/btp-resource-consumption-monitor/cf/node_modules/@sap/cds]

{
  build: {
    target: 'gen',
    tasks: [
      { for: 'hana', src: 'db', options: { model: ['db', 'srv', 'app'] }},
      { for: 'nodejs', src: 'srv', options: { model: ['db', 'srv', 'app'] }},
      { for: 'helm', src: '.', options: { model: ['db', 'srv', 'app', '.'] }},
      { for: 'cov2ap', src: 'srv', options: { model: ['db', 'srv', 'app'] }},
      { for: 'typescript', src: '.', options: { model: ['db', 'srv', 'app', '.'] }}
    ]
  }
}

........done > wrote output to:
   gen/chart/Chart.yaml
   gen/chart/charts/content-deployment/Chart.yaml
   gen/chart/charts/content-deployment/templates/_helpers.tpl
   gen/chart/charts/content-deployment/templates/job.yaml
   gen/chart/charts/content-deployment/templates/secret.yaml
   gen/chart/charts/content-deployment/templates/service-account.yaml
   gen/chart/charts/content-deployment/templates/service-binding.yaml
   gen/chart/charts/content-deployment/values.schema.json
   gen/chart/charts/content-deployment/values.yaml
   gen/chart/charts/service-instance/Chart.yaml
   gen/chart/charts/service-instance/templates/_helpers.tpl
   gen/chart/charts/service-instance/templates/servicebinding.yaml
   gen/chart/charts/service-instance/templates/serviceinstance.yaml
   gen/chart/charts/service-instance/values.schema.json
   gen/chart/charts/service-instance/values.yaml
   gen/chart/charts/web-application/Chart.yaml
   gen/chart/charts/web-application/templates/NOTES.txt
   gen/chart/charts/web-application/templates/_api.tpl
   gen/chart/charts/web-application/templates/_helpers.tpl
   gen/chart/charts/web-application/templates/api-rule.yaml
   gen/chart/charts/web-application/templates/deployment.yaml
   gen/chart/charts/web-application/templates/hpa.yaml
   gen/chart/charts/web-application/templates/network-policy.yaml
   gen/chart/charts/web-application/templates/pod-disruption-budget.yaml
   gen/chart/charts/web-application/templates/rbac.yaml
   gen/chart/charts/web-application/templates/secret.yaml
   gen/chart/charts/web-application/templates/service-account.yaml
   gen/chart/charts/web-application/templates/service-binding.yaml
   gen/chart/charts/web-application/templates/service.yaml
   gen/chart/charts/web-application/templates/virtual-service.yaml
   ... 225 more. Run with DEBUG=build to show all files.

TypeError: Cannot read properties of undefined (reading 'severity')
    at /home/user/projects/btp-resource-consumption-monitor/cf/node_modules/@sap/cds-dk/lib/build/buildTaskEngine.js:336:70
    at Array.filter (<anonymous>)
    at BuildTaskEngine._sortMessagesUnique (/home/user/projects/btp-resource-consumption-monitor/cf/node_modules/@sap/cds-dk/lib/build/buildTaskEngine.js:336:43)
    at BuildTaskEngine._resolveHandlerResponse (/home/user/projects/btp-resource-consumption-monitor/cf/node_modules/@sap/cds-dk/lib/build/buildTaskEngine.js:191:39)
    at BuildTaskEngine._executeBuildTasks (/home/user/projects/btp-resource-consumption-monitor/cf/node_modules/@sap/cds-dk/lib/build/buildTaskEngine.js:153:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BuildTaskEngine.processTasks (/home/user/projects/btp-resource-consumption-monitor/cf/node_modules/@sap/cds-dk/lib/build/buildTaskEngine.js:59:33)
    at async build (/home/user/projects/btp-resource-consumption-monitor/cf/node_modules/@sap/cds-dk/lib/build/index.js:19:16)
    at async Object.build (/home/user/projects/btp-resource-consumption-monitor/cf/node_modules/@sap/cds-dk/bin/build.js:171:5)
    at async Object.exec (/home/user/projects/btp-resource-consumption-monitor/cf/node_modules/@sap/cds-dk/bin/cds.js:94:16)
[2024-12-18 13:33:51] ERROR the "before-all"" build failed: could not execute the "npm run build:cf" command: exit status 1
make: *** [Makefile_20241218133342.mta:28: pre_build] Error 1
Error: could not build the MTA project: could not execute the "make -f Makefile_20241218133342.mta p=cf mtar= strict=true mode=" command: exit status 2

Regards,
Madhu M R

**Comment by willemi069808** [comment]
Hi Madhu,

This was just unfortunate timing. There was an issue with the `@sap/cds-dk` package and a fix has been published a few minutes ago, see https://www.npmjs.com/package/@sap/cds-dk?activeTab=versions. Please remove the `node_modules` folder and the `package-lock.json` file again, and run the install/build commands again.

It should now pick up the new `cds` version as per below sample:

```
...building project [..]
cds-dk [8.6.1], cds [8.6.0], compiler [5.6.0] ..
```

**Comment by madhumr3107** [comment]
Hi Willem,

Appericate for your quick support. Now i am able to build successfully. Thank you so much for help us resolve this error. Will raise the request in case faces any more issue or challenges.

Regards,
Madhu MR
