### ISSUE TITLE
Error while deploying 

### ISSUE THREAD

**Issue by alokva** [SAP-samples/btp-resource-consumption-monitor#7]
Hi,

I'm getting this below error while deploying the code. I've a subaccount with HANA Cloud and SAP build Workzone, also I made sure all the entitlements are available in this subaccount.

Also one suggestion, mar file name is btp-resource-consumption_1.0.0.mtar not BTPResourceConsumption_1.0.0.mtar so please change that accordingly.

**Error with creating a client for content service "btprc-dest": Error retrieving required property "uaa" for service key "btprc-dest-key" for service "btprc-dest"**

Thanks
Alok Varma

**Comment by alokva** [comment]
This error I'm getting in the 1st deployment.

**Comment by alokva** [comment]
One more confirmation I need, do we need the SAP Work zone in the same subaccount as HANA Cloud ?

**Comment by tedharrisLW** [comment]
I am getting this error as well with everything in the same subaccount.

**Comment by willemi069808** [comment]
Hi,

Thank you for opening this issue and spotting the error. This has been corrected now in 6bbcc08.

Regarding the location of HANA Cloud: your HANA Cloud database instance can sit in any CF org, space, or even other subaccount as long as you stay within the same region (e.g. eu20, ap10, ...). If you want to use a remote HANA Cloud database instance you have to make sure this HANA Cloud instance has been mapped/shared with the org/space in which you deploy the application (and the hdi instance). See [SAP Help - Map an SAP HANA Database to another Environment Context](https://help.sap.com/docs/hana-cloud/sap-hana-cloud-administration-guide/map-sap-hana-database-to-another-environment-context), or these quick steps for HANA Cloud Central:

1. On the All Instances page, click the "..." (More) icon in the Actions column.
2. Select Manage Configuration.
3. Select the Instance Mapping tab to show existing mappings.
4. Click the Edit button to add or delete a mapping.

Regarding the location of SAP Work Zone: Your SAP Work Zone subscription should reside in the same subaccount/org as where you deploy the application (and the ui5 applications are added to the HTML5 Application Repository Service). This is not necessarily the same subaccount as where your HANA Cloud database instance is deployed as mentioned above.

Hope this resolves the query

**Comment by alokva** [comment]
Thank you for the deployment fix. But this deployment should create the destination btprc-srv in the subaccount but it didn't create and due to this I'm not able to complete Step 2 of Work zone content where we need to specify the Runtime destination. 
Can you pls let me know if we are missing something in our yaml file ?

Thanks
Alok

**Comment by alokva** [comment]
Pls ignore, it did create. I was looking into a wrong subaccount.

Thanks

**Comment by tedharrisLW** [comment]
This fixed the deployment problem for me as well. However now I am getting a new issue. The home page loads in build workzone but when going to the BTP Resource Consumption it hangs and in the trace I get a btprcreport/Component-preload.js failed to load and Internal Server Error 500.

**Comment by alokva** [comment]
It worked for me completely and now I'm able to see the dashboard from Work zone.

**Comment by willemi069808** [comment]
As I’m not too sure what is happening on your side, please reach out to me via email/teams so we can look into it. My email is ***@***.***


From: Ted Harris ***@***.***>
Date: Tuesday, 26 March 2024 at 22:06
To: SAP-samples/btp-resource-consumption-monitor ***@***.***>
Cc: PARDAENS, Willem ***@***.***>, Comment ***@***.***>
Subject: Re: [SAP-samples/btp-resource-consumption-monitor] Error while deploying (Issue #7)

This fixed the deployment problem for me as well. However now I am getting a new issue. The home page loads in build workzone but when going to the BTP Resource Consumption it hangs and in the trace I get a btprcreport/Component-preload.js failed to load and Internal Server Error 500.
