### ISSUE TITLE
Unable to deploy - error create jobscheduler service key

### ISSUE THREAD

**Issue by js1972** [SAP-samples/btp-resource-consumption-monitor#8]
Hi. I am following the instructions to deploy this project but the mta deployment fails with:

```
Error monitoring creation or update of services: Error creating service "btprc-auth" from offering "xsuaa" and plan "application": Service broker error: Service broker xsuaa failed with: Error creating application null (Error parsing xs-security.json data: Could not find any xsuaa service for instance ID 6c03df46-64dd-418c-a774-3549457b93b5 and service name btprc-scheduler) 
Creating service key "btprc-scheduler-key" for service instance "btprc-scheduler"...
Creating service key "btprc-uas-key" for service instance "btprc-uas"...
Proceeding with automatic retry... (3 of 3 attempts left)
Creating service "btprc-auth" from MTA resource "btprc-auth"...
Async operation for service key of service instance "btprc-scheduler" failed with "10009 CF-UnableToPerform bind could not be completed: Service broker error: Service broker jobscheduler-broker failed with: The BTP Job Scheduling Service does currently not support the creation of service keys. Instead you have to bind an app for accessing this service instance."
A step of the process has failed. Retrying it may solve the issue.
```

I am trying to test this in a BTP trial account and have set the service plan to "lite" for the app logging service and the job scheduler service.

Any ideas?

**Comment by willemi069808** [comment]
Service plans named `lite` do not allow service key creation. So the deployment will fail for both the `Application Logging service` as well as the `Job Scheduling service` with these plans.

The purpose of this application is to monitor the credit consumption of the BTP account. Trial accounts are not credit-enabled so the application will have very limited use on trial accounts. For testing purposes it is advised to use free tier services in a CPEA/BTPEA account.

To continue the deployment on your end, you should remove the job scheduling service from the MTA as well as the code leveraging it in [server.ts#L91-101](https://github.com/SAP-samples/btp-resource-consumption-monitor/blob/main/cf/srv/server.ts#L91-L101). This will remove the scheduling aspect of the application and will require you to manually trigger the download of the latest data via the user interface (BTP Resource Consumption report > `Data Management` > `Load consumption for current month`).

For now, the application is not supported on trial as-is.

**Comment by js1972** [comment]
Great to know - I had no idea the lite plans don't allow service creation.
